### ISSUE TITLE
Home Assistant should check alerts and notify user

### ISSUE THREAD

**Issue by balloob** [home-assistant/alerts.home-assistant.io#8]
As a user, I want my Home Assistant instance to fetch the alerts.json file and notify me of any possible issues with my installation.

**Comment by SeanPM5** [comment]
With the news about Automatic service shutting down later this month, it reminded me of this issue. Did a mockup for how this could potentially be communicated via the new Integrations page.  

![alert](https://i.imgur.com/nvq7j7P.png)

Follows the same style that ignored (gray) and discovered (blue) integrations currently use in v0.109. But alerts would be yellow (`#FDD835`) with black (`#212121`) text. The "View Alert" button would take you to that specific page on the Home Assistant Alerts website. 

This would not help in all cases (such as this one) since not all integrations get shown on the Integrations page. But might be helpful for those that do...

**Comment by balloob** [comment]
Amazing, added to Figma mock up so we don't forget :)

**Comment by Kanga-Who** [comment]
AS per the (long) thread discussing the removal of RPI GPIO, I made this and then provided this thread. Can this idea be looked into further to help prevent future communication issues / appease people.
https://community.home-assistant.io/t/im-unhappy-with-the-removal-of-gpio/388578/380

**Comment by ludeeus** [comment]
<https://www.home-assistant.io/integrations/homeassistant_alerts/>
